# version: '3.8'

services:
  nextjs-app:
    image: milimol/magna-web:latest
    container_name: magna-web
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_ENDPOINT_URL="http://localhost:8000/api"
      - NEXT_PUBLIC_ENDPOINT_MEDIA="http://localhost:8002"
      - NEXT_PUBLIC_WEB_DOMAIN="http://localhost:3000"
      - NEXTAUTH_SECRET="5!=$jvjh3dxy4bd_t@+i%%hb2yhl4)k792ghz#rvq9jdr05h1^"
      - NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID="***********************************************************************"
      - NEXT_PUBLIC_GOOGLE_DRIVE_API_KEY="***************************************"
      - NEXT_PUBLIC_DROPBOX_API_KEY="csvat2185szgzjy"
      - NEXT_PUBLIC_BOX_CLIENT_ID="0w9g87g8gsjawlpo4cxy47fv663xyln8"
      - NEXT_PUBLIC_BOX_CLIENT_SECRET="r4cQ1W8hhFJiTOdWZKIo97eHr64Wa705"
      - NEXT_PUBLIC_MY_CASE_CLIENT_ID="KYbW86AP4x4xKEbc"
      - NEXT_PUBLIC_MY_CASE_CLIENT_SECRET="vA6iD9diiWJBSugrsLfGTCDEQeZ62m76"
    networks:
      - magna_shared_network
    command: yarn start
    mem_limit: 2g

networks:
  magna_shared_network:
    name: magna_shared_network
    driver: bridge
